### ISSUE TITLE
Replace with departmental assets

### ISSUE THREAD

**Issue by sumau** [LandRegistry/govuk-frontend-flask#23]
Many departments have their own assets e.g. MoJ https://design-patterns.service.justice.gov.uk/get-started/installing-compiled/. It would be really helpful if there was some instructions on how to replace the assets

**Comment by matthew-shaw** [comment]
Hi @sumau thanks for raising this issue.

The template was built for generic GOV.UK services, rather than allowing for departments to pull in their own assets. If you want to replace the govuk-frontend assets then lines 16, 17 and ~165 in the base template are where you need to look: https://github.com/LandRegistry/govuk-frontend-flask/blob/main/app/templates/base.html

If the MoJ Design System is built on top of the standard govuk-frontend classes then it should work if you can provide the right assets. The instructions in the link you provided above look like they would get you 90% of the way there.

Hope that helps. I'm going to close this issue as I don't think it's the responsibility of this project to define how it can work with other frontends / design systems.
